In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
arr = np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [3]:
np.diag(arr)

array([1, 4])

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a = np.random.rand(4,3)
a

array([[0.89862265, 0.39915182, 0.53921752],
       [0.7851154 , 0.88795477, 0.83616018],
       [0.47549413, 0.05050803, 0.49692014],
       [0.72481982, 0.41310105, 0.86828667]])

In [6]:
a = np.random.randn(4,3)
a

array([[ 7.10392712e-01,  1.36775217e+00,  1.16388825e+00],
       [-1.13518394e-03, -2.85255583e-01,  6.80890657e-02],
       [ 6.01168928e-01,  1.53508540e-01,  1.30277951e+00],
       [ 1.02775949e+00,  2.45250095e-02, -1.53485278e+00]])

In [7]:
a = np.random.randint(100)
a < 35

False

In [8]:
import re
l = "a,b c,d e f-9887;2BaB"
re.split(",| |-|;",l)

['a', 'b', 'c', 'd', 'e', 'f', '9887', '2BaB']

In [9]:
l = "EBOLA _VIRUS22"
l

'EBOLA _VIRUS22'

In [10]:
l[4:2:-1]

'AL'

In [11]:
arr = np.arange(45).reshape(3,3,5)
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [12]:
arr2 = arr.ravel()

In [13]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [19]:
arr2 = arr2.reshape(5,9)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [20]:
arr2.shape

(5, 9)

In [21]:
arr2.T

array([[ 0,  9, 18, 27, 36],
       [ 1, 10, 19, 28, 37],
       [ 2, 11, 20, 29, 38],
       [ 3, 12, 21, 30, 39],
       [ 4, 13, 22, 31, 40],
       [ 5, 14, 23, 32, 41],
       [ 6, 15, 24, 33, 42],
       [ 7, 16, 25, 34, 43],
       [ 8, 17, 26, 35, 44]])

In [22]:
arr.resize(5,9)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [23]:
arr.shape

(5, 9)

In [176]:
arr[-1]

array([36, 37, 38, 39, 40, 41, 42, 43, 44])

In [182]:
arr[1:4,2:-1]

array([[11, 12, 13, 14, 15, 16],
       [20, 21, 22, 23, 24, 25],
       [29, 30, 31, 32, 33, 34]])

In [164]:
arr[1:4,[1,2,6,7]]

array([[10, 11, 15, 16],
       [19, 20, 24, 25],
       [28, 29, 33, 34]])

In [158]:
arr = arr.reshape(3,-1)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [4]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

c = np.vstack((a,b))
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [5]:
d = np.hstack((a,b))
d

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [6]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [7]:
np.concatenate((a,b),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [9]:
np.column_stack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [10]:
np.row_stack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [11]:
a = np.array([1,2])
b = np.array([3,4])

np.column_stack((a,b))

array([[1, 3],
       [2, 4]])

In [12]:
np.row_stack((a,b))

array([[1, 2],
       [3, 4]])