## References: [http://cs231n.github.io/python-numpy-tutorial/#numpy-arrays]

In [1]:
import numpy as np

In [2]:
A = np.array([1,2,3])
A

array([1, 2, 3])

In [5]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

## Can be reshaped in multiples of 6 because there are 6 elements. 

In [6]:
A.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [9]:
A.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

## Some attributes

In [23]:
A.dtype

dtype('int32')

In [24]:
A.size

6

In [25]:
A.itemsize # In Bytes

4

In [26]:
A.shape

(2, 3)

## flatten() function

In [10]:
A.flatten()

array([1, 2, 3, 4, 5, 6])

## zeros() function

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## ones() function

In [17]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## arange(start,step,stop) or arange(start,stop)

In [18]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [20]:
np.arange(1,10,-2)

array([], dtype=int32)

## arange(start,stop) if start==stop we'll get empty array

In [22]:
np.arange(10,10)

array([], dtype=int32)

## sum() function

In [27]:
abc = np.array([[1,2,3],[1,2,3]])
np.sum(abc)

12

## Normal multiplication and dot() product

In [28]:
A = np.array([1,2,3])
B = np.array([2,2,2])
A * B

array([2, 4, 6])

In [29]:
np.dot(A,B)

12

## linspace() function -> Return evenly spaced numbers over a specified interval.

In [37]:
np.linspace(0, 5, 10) # Jana 5 tak ha per numbers 10 create krnay hain

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

## diag() function

In [47]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [48]:
np.diag((1,2,3))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

## linalg library of numpy (Scipy extension)

In [40]:
matrix = np.array([[4.3, 8.9],[2.2, 3.4]])
print(matrix)

[[4.3 8.9]
 [2.2 3.4]]


In [43]:
np.linalg.eig(matrix) # 1st vector is of eigen values and other vectors are eigen vectors

(array([ 8.29775224, -0.59775224]), array([[ 0.91219929, -0.87610148],
        [ 0.40974683,  0.48212674]]))

In [44]:
np.linalg.det(matrix)

-4.960000000000002

## full() function

In [49]:
np.full((2,2), 7)

array([[7, 7],
       [7, 7]])

## eye() function -> Identity Function

In [51]:
np.eye(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## random.random() function

In [52]:
np.random.random((2,2))

array([[0.47978479, 0.55169401],
       [0.11653224, 0.28589936]])

In [61]:
np.random.random([3,3])

array([[0.50071518, 0.23062055, 0.3174098 ],
       [0.35094224, 0.71352187, 0.70577214],
       [0.3965885 , 0.52780501, 0.95710566]])

In [66]:
np.random.rand((2,2)) # In rand() only integer can be passed

TypeError: 'tuple' object cannot be interpreted as an integer

In [67]:
np.random.rand(2)

array([0.28921309, 0.01399004])

In [69]:
np.random.randn(2) # Normally distributed values

array([0.3598363 , 0.78083021])

## Indexing

In [72]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
a[:2,1:3] # rows from 0 to 1 and columns from 1 to 2

array([[2, 3],
       [6, 7]])

In [82]:
a[0,1]

2

In [83]:
a[:,1]

array([ 2,  6, 10])

In [84]:
a[1,:]

array([5, 6, 7, 8])

## Boolean Indexing

In [87]:
a = np.array([[1,2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [89]:
boolean = a>2
boolean

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [90]:
a[boolean]

array([3, 4, 5, 6])

In [91]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [92]:
a[a>2]

array([3, 4, 5, 6])

## Broadcasting

In [93]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
