In [1]:
import numpy as np

In [3]:
ns = np.array(['1.25', '-9.6', '42'])

In [5]:
ns.astype('float64')

array([ 1.25, -9.6 , 42.  ])

In [7]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [8]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [9]:
bools = np.array([False, False, True, False])
bools.any()

True

In [10]:
bools.all()

False

In [22]:
bools = np.array([1, 0, 0, 0])
bools.any()

True

In [23]:
bools = np.array([1, 1, 1, 1])
bools.all()

True

In [24]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [27]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [28]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [29]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

In [30]:
arr = np.array([[123,-34,678],[-23,32,-98],[-100,0,100]])
arr

array([[ 123,  -34,  678],
       [ -23,   32,  -98],
       [-100,    0,  100]])

In [35]:
from numpy.linalg import svd
svd(arr)

(array([[-0.98238093, -0.10799903,  0.15252517],
        [ 0.14527701,  0.07211436,  0.9867594 ],
        [-0.11756831,  0.99153201, -0.055154  ]]),
 array([702.15114688, 115.79890787,  26.46469116]),
 array([[-0.16010427,  0.05419035, -0.9856115 ],
        [-0.98529178,  0.05163802,  0.16289146],
        [ 0.05972217,  0.99719453,  0.04512584]]))